### ISSUE TITLE
Warning message for deprecated yaml.load() call

### ISSUE THREAD

**Issue by DebyKatz** [ChrisTimperley/roswire#322]
/usr0/home/dskatz/.local/share/virtualenvs/overhead-timing-effects-in-ROS-Wl9qFQgJ/lib/python3.6/site-packages/roswire/proxy/service.py:71: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  d = yaml.load(output)

**Comment by ChrisTimperley** [comment]
Kinda weird that GitHub didn't automatically close this issue. Anyway, this should be fixed.
