### ISSUE TITLE
Implement read method for ROS2LaunchManager

### ISSUE THREAD

**Issue by ChrisTimperley** [ChrisTimperley/roswire#373]
General approach:
* copy ROS2 launch file parser script into container
* run script inside container (via `app_instance.shell`)
* copy or read JSON output from script
* convert JSON output to LaunchConfig

Will probably need to:
* move across the ROS2 launch file parser and make sure file ends with `.py_`
* add ROS2 launch file parser to `MANIFEST.in`

**Comment by schmerl** [comment]
Add code to: https://github.com/ChrisTimperley/roswire/blob/master/src/roswire/ros2/launch.py ::read

**Comment by schmerl** [comment]
When running against this launch file: https://github.com/ROBOTIS-GIT/turtlebot3_simulations/blob/foxy-devel/turtlebot3_gazebo/launch/empty_world.launch.py, I get the errors:

```
UNKNOWN ENTITY: <class 'launch.actions.execute_process.ExecuteProcess'>
UNKNOWN ENTITY: <class 'launch.actions.execute_process.ExecuteProcess'>
urdf_file_name : turtlebot3_burger.urdf
UNKNOWN ENTITY: <class 'launch.actions.set_launch_configuration.SetLaunchConfiguration'>
UNKNOWN ENTITY: <class 'launch.actions.declare_launch_argument.DeclareLaunchArgument'>
root@19aa61bedc80:/# source /opt/ros/foxy/setup.bash
root@19aa61bedc80:/# python3 launch_extractor.py /ros_ws/install/turtlebot3_gazebo/share/turtlebot3_gazebo/launch/empty_world.launch.py
UNKNOWN ENTITY: <class 'launch.actions.execute_process.ExecuteProcess'>
UNKNOWN ENTITY: <class 'launch.actions.execute_process.ExecuteProcess'>
urdf_file_name : turtlebot3_burger.urdf
UNKNOWN ENTITY: <class 'launch.actions.set_launch_configuration.SetLaunchConfiguration'>
UNKNOWN ENTITY: <class 'launch.actions.declare_launch_argument.DeclareLaunchArgument'>
```
The resulting arch.json looks like:
```
[
  {
    "name": "robot_state_publisher",
    "executable": "robot_state_publisher",
    "package": "robot_state_publisher"
  }
]
```
So it is missing some information (like launching gazebo). We need to be able to process this stuff too.
