### ISSUE TITLE
Improve performance of ROS2 package path calculation

### ISSUE THREAD

**Issue by ChrisTimperley** [ChrisTimperley/roswire#415]
It currently takes a little over 2 minutes to execute `PackagePath._paths_ros2` for an app that contains a little over 100 packages. The issue is that the current implementation involves O(n + 1) calls to `ros2 pkg`. We can replace this by a single shell call by interacting with `ament_index_python.packages.get_packages_with_prefixes`.

https://github.com/ament/ament_index/blob/master/ament_index_python/ament_index_python/packages.py#L26

**Comment by schmerl** [comment]
This can probably be implemented with something like:

```
python -c "import json; import ament_index_python; json.dump(ament_index_python.get_packages_with_prefixes())"
```
